### ISSUE TITLE
Docs deployed only with index

### ISSUE THREAD

**Issue by fabraz** [fastai/nbdev_template#44]
Hi there,

I was wondering what can be wrong with my documents deployment. You may find it in the following url: 

fabraz.github.io/fastagger/

The only thing that loads is the index page without sidebar, header.

The same documentation works like a charm in local Jekyll

The project is on the following URL: 

https://github.com/fabraz/fastagger

Thanks in advance!

**Comment by ronaldokun** [comment]
I have the same issue. There is no error in the build, but the docs don't have a header nor a sidebar.

**Comment by hamelsmu** [comment]
I've tried really hard to debug this issue, and I am also not sure remote themes seem to be failing.  I've reached out to GitHub internally (I work there )to try to help me.  

cc: @jph00

**Comment by hamelsmu** [comment]
Actually nevermind, I had a different kind of user error because I didn't spell the name of my repo correctly 🤦🏽 .  However, I found the issue is you aren't using the latest version of nbdev.  

I was able to fork your repo and have GitHub Pages build your `fastgagger` site correctly: https://hamelsmu.github.io/fastagger/ via https://github.com/hamelsmu/fastagger/

You can fix your issues by updating your version of nbdev and rebuilding your docs with the running the following commands
```
pip install -U nbdev
nbdev_build_lib && nbdev_clean_nbs && nbdev_build_docs
git add -A; git commit -m'save docs files'; git push
```

Enjoy

**Comment by hamelsmu** [comment]
FYI I added troubleshooting steps to the README that covers this and other common errors.  Thanks, hope that helps.

**Comment by fabraz** [comment]
@hamelsmu, thanks for your effort trying to solve this issue. 

Actually, conda list showed the following:
> nbdev                     1.1.13                     py_0    fastai

Its incredible that your https://hamelsmu.github.io/fastagger/  docs is perfect and mine not. The mystery holds.

Its worth mention that I've also tried a new repo using ubuntu without conda. The problem still the same.

> https://github.com/fabraz/vigilant ->  https://fabraz.github.io/vigilant/
