### ISSUE TITLE
"Could not locate Gemfile" on `bundle install` to serve docs locally

### ISSUE THREAD

**Issue by shubhvachher** [fastai/nbdev_template#75]
Used the template. Ran `nbdev_build_docs`. cd into the docs folder and ran `bundle install` and failed with the error "Could not locate Gemfile"

**Solved** by using the Gemfile and Gemfile.lock at repository history https://github.com/fastai/nbdev_template/tree/fe3ae318a412163db604457ca7ed62380934290e/docs

@muellerzr was there a reason you deleted these files in your recent commits (https://github.com/fastai/nbdev_template/commits/master/docs) ? I'm new to nbdev so... are these files supposed to be autogenerated by nbdev_build_docs or something?

**Comment by shubhvachher** [comment]
It also probably breaks the "Helper Script to use nbdev remote theme" at https://gist.github.com/hamelsmu/977e82a23dcd8dcff9058079cb4a8f18#file-nbdev_jekyll-py-L17

@hamelsmu

**Comment by muellerzr** [comment]
@shubhvachher one option is adjust the script to be:

`raw = https://raw.githubusercontent.com/fastai/nbdev-jekyll-theme/master/`

We tried removing the Gemfile because it causes security issues each time something has an error, and when you (perhaps) have 10+ nbdev_template repos, you can imagine how frustrating that can be.

I'll be trying to work on the solution for this one

**Comment by shubhvachher** [comment]
> We tried removing the Gemfile because it causes security issues each time something has an error,

This sounds a bit ominous. As someone who is primarily a Python user and doesn't understand Jekyll, what do you mean? @muellerzr

**Comment by hamelsmu** [comment]
It doesn't actually cause a security issue it just creates a security warning, which you may or may not pay attention to depending on your situation.  If you are using nbdev with GitHub pages you can safely ignore the warnings
